# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created


name: Publish Patch to NPM
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencie 🔧
        run: npm install
      # Config git
      - name: Commit package.json changes and create tag
        run: |
          git config --global user.name "${{ secrets.GH_NAME }}"
          git config --global user.email "${{ secrets.GH_EMAIL }}"
      # Bump package version
      # Use tag latest
      - name: Bump release version
        run: |
          npm --no-git-tag-version version patch
          git add .
          git commit -m "chore: release patch"
      - name: Publish package on NPM 📦
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_ACCESS_TOKEN }}